# kind-cluster-config.yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: clovis-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.29.0
  - role: worker
    image: kindest/node:v1.29.0
  - role: worker
    image: kindest/node:v1.29.0

